/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projetocompfisica;

import Arduino.AcessaArduino;
import Banco.Iluminaçao;
import Banco.IluminaçaoDao;
import java.awt.Color;
import java.util.Date;
import java.util.concurrent.TimeUnit;

    
/**
 *
 * @author Felipe
 */
public class Interface extends javax.swing.JFrame {

        AcessaArduino acessaArduino;
        long tempo1;
        long tempo2;
        long tempo3;
        long tempo4;
        IluminaçaoDao ilu = new IluminaçaoDao();
        Iluminaçao reg = new Iluminaçao();
        
        public void windowClosing(java.awt.event.WindowEvent e){
          acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "2");  
          acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "4");
          acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "6");
          acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "8");
        }
       

    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
              
        try {
            acessaArduino = new AcessaArduino();
            System.out.println("porta detectada: " + acessaArduino.getPortaSelecionada());
            
        } catch (Exception e) {
            System.out.println("Erro ao acionar o arduino");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botao1 = new javax.swing.JToggleButton();
        botao2 = new javax.swing.JToggleButton();
        botao3 = new javax.swing.JToggleButton();
        botao4 = new javax.swing.JToggleButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botao1.setForeground(new java.awt.Color(255, 51, 51));
        botao1.setText("Luzes Quarto");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        botao2.setForeground(new java.awt.Color(255, 51, 51));
        botao2.setText("Luzez Cozinha");
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });

        botao3.setForeground(new java.awt.Color(255, 51, 51));
        botao3.setText("Luzes Sala");
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });

        botao4.setForeground(new java.awt.Color(255, 51, 51));
        botao4.setText("Luzes Suite");
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addGap(25, 25, 25))
        );

        jButton1.setText("Estatísticas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        if (botao1.isSelected()){
            acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "1");
            botao1.setForeground(Color.green);
            tempo1=System.currentTimeMillis();
            }
        else{
        acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "2");
            botao1.setForeground(Color.red);
            tempo1=tempo1-System.currentTimeMillis();
            tempo1=tempo1*-1;
            tempo1=TimeUnit.MILLISECONDS.toSeconds(tempo1);
            System.out.println(tempo1);
            reg.setNumLampada(1);
            reg.setTempoAceso(tempo1);
            ilu.persist(reg);
        }
    }//GEN-LAST:event_botao1ActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
       if (botao2.isSelected()){
            acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "3");
            botao2.setForeground(Color.green);
            tempo2=System.currentTimeMillis();
        }
        else{
        acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "4");
            botao2.setForeground(Color.red);
            tempo2=tempo2-System.currentTimeMillis();
            tempo2=tempo2*-1;
            tempo2=TimeUnit.MILLISECONDS.toSeconds(tempo2);
            System.out.println(tempo2);
            reg.setNumLampada(2);
            reg.setTempoAceso(tempo2);
            ilu.persist(reg);
        }       
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        if (botao3.isSelected()){
            acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "5");
            botao3.setForeground(Color.green);
            tempo3=System.currentTimeMillis();
        }
        else{
        acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "6");
            botao3.setForeground(Color.red);
            tempo3=tempo3-System.currentTimeMillis();
            tempo3=tempo3*-1;
            tempo3=TimeUnit.MILLISECONDS.toSeconds(tempo3);
            System.out.println(tempo3);
            reg.setNumLampada(3);
            reg.setTempoAceso(tempo3);
            ilu.persist(reg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_botao3ActionPerformed

    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
        if (botao4.isSelected()){
            acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "7");
            botao4.setForeground(Color.green);
            tempo4=System.currentTimeMillis();
        }
        else{
        acessaArduino.setDataToArduino(acessaArduino.getSerialPort(), "8");
            botao4.setForeground(Color.red);
            tempo4=tempo4-System.currentTimeMillis();
            tempo4=tempo4*-1;
            tempo4=TimeUnit.MILLISECONDS.toSeconds(tempo4);
            System.out.println(tempo4);
            reg.setNumLampada(4);
            reg.setTempoAceso(tempo4);
            ilu.persist(reg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_botao4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Grafico g= new Grafico("Teste", "Teste1");
     g.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botao1;
    private javax.swing.JToggleButton botao2;
    private javax.swing.JToggleButton botao3;
    private javax.swing.JToggleButton botao4;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
